# ==============================================================================
#   /$$      /$$  /$$$$$$  /$$$$$$$  /$$   /$$ /$$$$$$ /$$   /$$  /$$$$$$ 
#  | $$  /$ | $$ /$$__  $$| $$__  $$| $$$ | $$|_  $$_/| $$$ | $$ /$$__  $$
#  | $$ /$$$| $$| $$  \ $$| $$  \ $$| $$$$| $$  | $$  | $$$$| $$| $$  \__/
#  | $$/$$ $$ $$| $$$$$$$$| $$$$$$$/| $$ $$ $$  | $$  | $$ $$ $$| $$ /$$$$
#  | $$$$_  $$$$| $$__  $$| $$__  $$| $$  $$$$  | $$  | $$  $$$$| $$|_  $$
#  | $$$/ \  $$$| $$  | $$| $$  \ $$| $$ \  $$  | $$  | $$\  $$$| $$  \ $$
#  | $$/   \  $$| $$  | $$| $$  | $$| $$  \ $$ /$$$$$$| $$ \  $$|  $$$$$$/
#  |__/     \__/|__/  |__/|__/  |__/|__/  \__/|______/|__/  \__/ \______/ 
#                                                                           
#   [!] CRITICAL: IF YOU CAN READ THIS, PLEASE FORK FIRST!
# ==============================================================================
#   
#   DO NOT EDIT THIS FILE DIRECTLY IN THE MASTER BRANCH.
#   
#   1. FORK this repository to your own GitHub account.
#   2. CREATE 'profiles.json' based on your local environment.
#   3. NEVER commit 'session_cookies.json' to a public repo (Account Theft Risk).
#   
#   "With great power comes great automation." - Use Responsibly.
# ==============================================================================

import os
import time
import json
import random
import threading
import sys
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

try:
    from pynput import keyboard
except ImportError:
    print("\033[91m[!] Error: Library 'pynput' not installed.\033[0m")
    print("Run: pip install pynput")
    sys.exit()

G, R, Y, C, W, B = '\033[92m', '\033[91m', '\033[93m', '\033[96m', '\033[0m', '\033[94m'

DATA_FILE 	= "profiles.json"		// PROFILES PATH FOR YOUR BROWSER
COOKIE_FILE 	= "session_cookies.json"	// SESSION FOR LIKE4LIKE.ORG
ERROR_IMG 	= "error_snapshot.png"		// ERROR log

STOP_BOT = False

PLATFORM_SCRIPTS = {
    "YouTube": """
        var target = document.querySelector('yt-animated-icon[animated-icon-type*="LIKE"]') ||
                     document.querySelector('button[aria-label*="like this video"]') ||
                     document.querySelector('button[aria-label*="Like this video"]');
        
        if (target) {
            var btn = target.tagName === 'BUTTON' ? target : target.closest('button');
            if (btn) {
                if (btn.getAttribute('aria-pressed') === 'true') return "ALREADY_LIKED";
                btn.click();
                return "CLICKED";
            }
        }
        return "NOT_FOUND";
    """,
    "Twitter": """
        var btn = document.querySelector('button[data-testid="like"]');
        if (btn) {
            var label = btn.getAttribute('aria-label') || "";
            if (label.toLowerCase().includes('unlike')) return "ALREADY_LIKED";
            btn.click();
            return "CLICKED";
        }
        return "NOT_FOUND";
    """,
    "Instagram": """
        var unlikeSvg = document.querySelector('svg[aria-label="Unlike"]') || 
                        document.querySelector('svg[aria-label="Batal suka"]');
        if (unlikeSvg) return "ALREADY_LIKED";

        var allLikes = document.querySelectorAll('svg[aria-label="Like"], svg[aria-label="Suka"]');
        var targetLike = null;

        for (var i = 0; i < allLikes.length; i++) {
            var rect = allLikes[i].getBoundingClientRect();
            if (rect.width > 20) {
                targetLike = allLikes[i];
                break; 
            }
        }
        
        if (targetLike) {
            var btn = targetLike.closest('[role="button"]');
            if (btn) { btn.click(); return "CLICKED_BTN"; }
            var clickEvent = new MouseEvent("click", { "view": window, "bubbles": true, "cancelable": false });
            targetLike.dispatchEvent(clickEvent);
            return "CLICKED_SVG_FORCE";
        }
        return "NOT_FOUND";
    """
}

def human_sleep(min_sec=2.0, max_sec=5.0):
    sleep_time = random.triangular(min_sec, max_sec, (min_sec+max_sec)/2)
    time.sleep(sleep_time)

def on_press(key):
    global STOP_BOT
    if key == keyboard.Key.esc:
        STOP_BOT = True
        return False

def start_keyboard_listener():
    global STOP_BOT
    STOP_BOT = False
    listener = keyboard.Listener(on_press=on_press)
    listener.start()

def clear_screen(): os.system('clear')

def load_data():
    if not os.path.exists(DATA_FILE):
        print(f"\n{R}[!] FATAL ERROR: Configuration file '{DATA_FILE}' not found.{W}")
        print(f"{Y}[*] Please create '{DATA_FILE}' manually or copy from example.{W}")
        print(f"{C}    Example structure:{W}")
        print(f"""    {{
        "active_index": 0,
        "accounts": [
            {{ "name": "My Profile", "path": "/path/to/firefox/profile" }}
        ]
    }}""")
        sys.exit()
        
    try:
        with open(DATA_FILE, "r") as f:
            return json.load(f)
    except json.JSONDecodeError:
        print(f"\n{R}[!] FATAL ERROR: '{DATA_FILE}' is not valid JSON.{W}")
        sys.exit()

def show_banner(data, mode_text="STABLE RELEASE"):
    try:
        active = data["accounts"][data["active_index"]]
        active_name = active['name']
    except:
        active_name = "Unknown"

    print(f"""{G}
  _      _  _     _                   _         _        ____        _       
 | |    | || |   | |                 / \  _   _| |_ ___ | __ )  ___ | |_ ___ 
 | |    | || |_  | |      ______    / _ \| | | | __/ _ \|  _ \ / _ \| __/ __|
 | |___ |__   _| | |___  |______|  / ___ \ |_| | || (_) | |_) | (_) | |_\__ \\
 |_____|   |_|   |_____|          /_/   \_\__,_|\__\___/|____/ \___/ \__|___/
                                                          
           -- Created By LoGoRo17 --{W}""")
    print(f"{C}Version: {Y}v1.0.0{W} | {G}Mode: {mode_text}{W}")
    print(f"{C}Active : {Y}{active_name}{W}")
    print(f"{C}Info   : {R}Press 'Esc' to STOP safely.{W}")
    print(f"{C}" + "="*58 + f"{W}")

def inject_cookies(driver):
    driver.get("https://www.like4like.org/login/")
    if os.path.exists(COOKIE_FILE):
        try:
            with open(COOKIE_FILE, 'r') as f:
                cookies = json.load(f)
                for cookie in cookies:
                    try:
                        if 'expiry' in cookie: del cookie['expiry']
                        if 'sameSite' in cookie: del cookie['sameSite']
                        driver.add_cookie(cookie)
                    except: pass
        except: pass
    driver.get("https://www.like4like.org/user/dashboard.php")

def perform_native_double_click(driver):
    try:
        action = ActionChains(driver)
        try: target = driver.find_element(By.TAG_NAME, "video")
        except: target = driver.find_element(By.TAG_NAME, "body") 
        action.move_to_element(target).double_click().perform()
        return True
    except: return False

def update_dashboard(data, repetition, target):
    clear_screen()
    show_banner(data, "NORMAL DASHBOARD MODE")
    percent = int((repetition / target) * 100) if target > 0 else 0
    bar_length = 30
    filled_length = int(bar_length * repetition // target) if target > 0 else 0
    bar = '█' * filled_length + '-' * (bar_length - filled_length)
    print(f"\n{G}Progress : |{bar}| {percent}%{W}")
    print(f"{G}Status   : {repetition}/{target} Points Claimed{W}")
    if STOP_BOT: print(f"\n{R}[!] STOPPING BOT... PLEASE WAIT...{W}")

def auto_earn_logic(driver, social_name, debug_mode, target_limit):
    global STOP_BOT
    data = load_data()
    repetition_count = 0
    consecutive_retries = 0 
    MAX_RETRIES = 5         
    current_js_script = PLATFORM_SCRIPTS.get(social_name)
    
    start_keyboard_listener()

    if not debug_mode:
        update_dashboard(data, repetition_count, target_limit)
    else:
        print(f"{G}[+] Bot Active. Target: {target_limit} Likes.{W}")

    while not STOP_BOT:
        if repetition_count >= target_limit:
            print(f"\n{G}[★] TARGET REACHED. JOB DONE.{W}")
            break

        try:
            wait = WebDriverWait(driver, 10)
            
            try:
                if STOP_BOT: break
                like_btn = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "a.pulse-checkBox")))
                if debug_mode: print(f"{C}[*] Task detected.{W}")
                consecutive_retries = 0 
                driver.execute_script("arguments[0].click();", like_btn)
            except:
                if STOP_BOT: break
                consecutive_retries += 1
                print(f"{Y}[!] No task found. Retry {consecutive_retries}/{MAX_RETRIES}...{W}")
                
                if consecutive_retries >= MAX_RETRIES:
                    print(f"\n{R}[!] No tasks available after {MAX_RETRIES} attempts.{W}")
                    print(f"{R}[!] Returning to Main Menu...{W}")
                    time.sleep(3)
                    break 
                
                driver.refresh()
                human_sleep(3, 5)
                continue
            
            if STOP_BOT: break
            main_window = driver.current_window_handle
            wait.until(lambda d: len(d.window_handles) > 1)
            for handle in driver.window_handles:
                if handle != main_window:
                    driver.switch_to.window(handle)
                    break

            success_render = False
            if debug_mode: print(f"{Y}[!] Waiting for page load (Max 20s)...{W}")
            
            for _ in range(20):
                if STOP_BOT: break
                if driver.execute_script("return document.readyState") == "complete":
                    if driver.execute_script("return document.body !== null;"):
                        success_render = True
                        break
                time.sleep(1)
            
            if STOP_BOT: driver.close(); driver.switch_to.window(main_window); break

            if success_render:
                if social_name == "YouTube":
                    if debug_mode: print(f"{C}[*] YouTube detected. Watching video (5s)...{W}")
                    time.sleep(random.uniform(10.0, 17.0))
                else:
                    human_sleep(2, 3)

                if "login" in driver.current_url:
                    if debug_mode: print(f"{R}[!] POP-UP LOGIN PAGE DETECTED!{W}")
                    driver.close(); driver.switch_to.window(main_window); break

                result = driver.execute_script(current_js_script)
                
                if "CLICKED" in result:
                    if debug_mode: print(f"{G}[✔] Liked via JS ({result}){W}")
                    human_sleep(2, 3)
                elif result == "ALREADY_LIKED":
                    if debug_mode: print(f"{Y}[!] Already Liked.{W}")
                else:
                    if social_name == "Instagram":
                        if debug_mode: print(f"{Y}[!] Selector fail. Trying NATIVE DOUBLE CLICK...{W}")
                        perform_native_double_click(driver)
                        if debug_mode: print(f"{G}[✔] Double Click Performed.{W}")
                        human_sleep(2, 3)
                    else:
                        if debug_mode: print(f"{R}[!] Button not found.{W}")
            else:
                 if debug_mode: print(f"{R}[!] TIMEOUT.{W}")
                 driver.save_screenshot(ERROR_IMG)
            
            try:
                driver.close()
                driver.switch_to.window(main_window)
            except:
                driver.switch_to.window(main_window)

            if STOP_BOT: break

            if debug_mode: print(f"{Y}[*] Confirming...{W}")
            try:
                confirm_btn = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "a.pulse-checkBox img[alt*='Confirm'], a.pulse-checkBox[onclick*='confirm']")))
                human_sleep(1.5, 3.0)
                if STOP_BOT: break
                
                parent_a = driver.execute_script("return arguments[0].parentNode;", confirm_btn)
                driver.execute_script("arguments[0].click();", parent_a)
                
                repetition_count += 1
                if debug_mode:
                    print(f"{G}[+] Point Claimed! Total: {repetition_count}/{target_limit}{W}")
                else:
                    update_dashboard(data, repetition_count, target_limit)
            except:
                if debug_mode: print(f"{R}[!] Confirm failed.{W}")

            human_sleep(3, 6)
            
        except Exception as e:
            if debug_mode: print(f"{Y}[!] Retry: {e}{W}")
            driver.refresh()
            human_sleep(5, 7)
    
    print(f"\n{G}[✔] SESSION ENDED.{W}")

def run_automation(social_name, target_url, debug_mode, target_limit):
    data = load_data()
    profile_path = data["accounts"][data["active_index"]]["path"]
    options = Options()
    options.add_argument("-profile")
    options.add_argument(profile_path)
    options.set_preference("dom.webdriver.enabled", False)
    
    driver = webdriver.Firefox(options=options)
    try:
        inject_cookies(driver)
        time.sleep(3)
        
        if "login.php" in driver.current_url or "welcome" in driver.current_url:
            print(f"\n{Y}[!] Session expired. AUTO-LOGIN FAILED.{W}")
            print(f"{G}[*] Please LOGIN MANUALLY in the browser now.{W}")
            print(f"{C}[*] The bot is waiting... (Press Enter here after you login){W}")
            input() 
            print(f"{G}[+] Saving new session cookies...{W}")
            cookies = driver.get_cookies()
            with open(COOKIE_FILE, 'w') as f: json.dump(cookies, f)

        driver.get(target_url)
        if "login.php" in driver.current_url:
             print(f"{R}[!] Login failed. Exiting.{W}")
             return

        if debug_mode: print(f"\n{G}[+] Login Verified. Starting Bot...{W}")
        else: time.sleep(1)
            
        auto_earn_logic(driver, social_name, debug_mode, target_limit)
    finally:
        driver.quit()

def earn_menu():
    while True:
        clear_screen()
        data = load_data()
        show_banner(data)
        print(f"\n{G}--- SELECT CATEGORY ---{W}")
        print(f"{G}[1]{W} YouTube Likes")
        print(f"{G}[2]{W} Twitter Favorites")
        print(f"{G}[3]{W} Instagram Likes")
        print(f"{B}[B]{W} Back")
        
        choice = input(f"\n{C}Choice : {W}").lower()
        targets = {
            "1": ("YouTube", "https://www.like4like.org/user/earn-youtube.php"),
            "2": ("Twitter", "https://www.like4like.org/user/earn-twitter-favorites.php"),
            "3": ("Instagram", "https://www.like4like.org/user/earn-instagram-like.php")
        }
        
        if choice in targets:
            name, url = targets[choice]
            print(f"\n{G}--- CONFIGURATION ---{W}")
            print(f"{G}[1]{W} Run as Normal (Dashboard)")
            print(f"{G}[2]{W} Run with Debug (Logs)")
            mode = input(f"{C}Mode : {W}")
            
            try:
                limit_input = input(f"{C}Set Target Likes (Default 100) : {W}")
                target_limit = int(limit_input) if limit_input.strip() else 100
            except:
                target_limit = 100

            run_automation(name, url, debug_mode=(mode == '2'), target_limit=target_limit)
        elif choice == 'b':
            break

def main():
    while True:
        data = load_data()
        clear_screen()
        show_banner(data)
        print(f"{G}[1]{W} Run AutoBot")
        print(f"{G}[2]{W} Manage Profiles")
        print(f"{G}[4]{W} Quit")
        choice = input(f"\n{C}Enter Number : {W}")
        if choice == '1': earn_menu()
        elif choice == '4': break

if __name__ == "__main__":
    main()
